// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sentinel/subscription/v3/params.proto

package v3

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	MaxAllocations int64                       `protobuf:"varint,1,opt,name=max_allocations,json=maxAllocations,proto3" json:"max_allocations,omitempty"`
	StakingShare   cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=staking_share,json=stakingShare,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"staking_share"`
	StatusTimeout  time.Duration               `protobuf:"bytes,3,opt,name=status_timeout,json=statusTimeout,proto3,stdduration" json:"status_timeout"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_c44cea6941fab3f5, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "sentinel.subscription.v3.Params")
}

func init() {
	proto.RegisterFile("sentinel/subscription/v3/params.proto", fileDescriptor_c44cea6941fab3f5)
}

var fileDescriptor_c44cea6941fab3f5 = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x4f, 0x4b, 0xfb, 0x30,
	0x1c, 0xc6, 0x9b, 0xdf, 0x60, 0xfc, 0xac, 0x6e, 0x42, 0xf1, 0x50, 0x27, 0x64, 0x43, 0x11, 0x77,
	0x31, 0xc1, 0xf5, 0x15, 0x38, 0x76, 0x10, 0xf1, 0x20, 0xd3, 0x93, 0x97, 0x91, 0x76, 0x69, 0x1b,
	0xd6, 0xf6, 0x5b, 0x9a, 0xb4, 0x6c, 0xef, 0xc2, 0xa3, 0x2f, 0xc1, 0x77, 0xe2, 0x8e, 0x3b, 0x8a,
	0x87, 0xa9, 0xdd, 0x1b, 0x91, 0xa5, 0x9b, 0x7f, 0x6e, 0xc9, 0xc3, 0xe7, 0xc3, 0xf3, 0x90, 0x98,
	0xa7, 0x92, 0x27, 0x4a, 0x24, 0x3c, 0xa2, 0x32, 0x77, 0xa5, 0x97, 0x89, 0x54, 0x09, 0x48, 0x68,
	0xe1, 0xd0, 0x94, 0x65, 0x2c, 0x96, 0x24, 0xcd, 0x40, 0x81, 0x65, 0x6f, 0x31, 0xf2, 0x1b, 0x23,
	0x85, 0xd3, 0x3a, 0x08, 0x20, 0x00, 0x0d, 0xd1, 0xf5, 0xa9, 0xe2, 0x5b, 0x38, 0x00, 0x08, 0x22,
	0x4e, 0xf5, 0xcd, 0xcd, 0x7d, 0x3a, 0xce, 0x33, 0xa6, 0x15, 0x9d, 0x1c, 0xbf, 0x20, 0xb3, 0x7e,
	0xab, 0x0b, 0xac, 0x33, 0x73, 0x3f, 0x66, 0xd3, 0x11, 0x8b, 0x22, 0xf0, 0x34, 0x22, 0x6d, 0xd4,
	0x41, 0xdd, 0xda, 0xb0, 0x19, 0xb3, 0xe9, 0xe5, 0x4f, 0x6a, 0x5d, 0x99, 0x0d, 0xa9, 0xd8, 0x44,
	0x24, 0xc1, 0x48, 0x86, 0x2c, 0xe3, 0xf6, 0xbf, 0x0e, 0xea, 0xee, 0xf4, 0x4f, 0xe6, 0xcb, 0xb6,
	0xf1, 0xb6, 0x6c, 0x1f, 0x79, 0x20, 0x63, 0x90, 0x72, 0x3c, 0x21, 0x02, 0x68, 0xcc, 0x54, 0x48,
	0x6e, 0x78, 0xc0, 0xbc, 0xd9, 0x80, 0x7b, 0xc3, 0xbd, 0x8d, 0x79, 0xb7, 0x16, 0xad, 0x6b, 0xb3,
	0x29, 0x15, 0x53, 0xb9, 0x1c, 0x29, 0x11, 0x73, 0xc8, 0x95, 0x5d, 0xeb, 0xa0, 0xee, 0x6e, 0xef,
	0x90, 0x54, 0xb3, 0xc9, 0x76, 0x36, 0x19, 0x6c, 0x66, 0xf7, 0xff, 0xaf, 0x5b, 0x9e, 0xde, 0xdb,
	0x68, 0xd8, 0xa8, 0xd4, 0xfb, 0xca, 0xec, 0xfb, 0xf3, 0x4f, 0x6c, 0x3c, 0x97, 0xd8, 0x98, 0x97,
	0x18, 0x2d, 0x4a, 0x8c, 0x3e, 0x4a, 0x8c, 0x1e, 0x57, 0xd8, 0x58, 0xac, 0xb0, 0xf1, 0xba, 0xc2,
	0xc6, 0xc3, 0x20, 0x10, 0x2a, 0xcc, 0x5d, 0xe2, 0x41, 0x4c, 0xb7, 0xcf, 0x78, 0x0e, 0xbe, 0x2f,
	0x3c, 0xc1, 0xa2, 0xef, 0x24, 0xcc, 0x5d, 0x5a, 0x5c, 0xf4, 0xe8, 0xf4, 0xef, 0x47, 0xa8, 0x59,
	0xca, 0x25, 0x2d, 0x1c, 0xb7, 0xae, 0x37, 0x39, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x88,
	0xc1, 0x2e, 0xb1, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.StatusTimeout, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.StatusTimeout):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x1a
	{
		size := m.StakingShare.Size()
		i -= size
		if _, err := m.StakingShare.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.MaxAllocations != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxAllocations))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxAllocations != 0 {
		n += 1 + sovParams(uint64(m.MaxAllocations))
	}
	l = m.StakingShare.Size()
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.StatusTimeout)
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAllocations", wireType)
			}
			m.MaxAllocations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxAllocations |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingShare", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StakingShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusTimeout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.StatusTimeout, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
