name: "Release"

on:
  release:
    types:
      - published

jobs:
  artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Build and Tag Docker Image
        run: make build-image

      - name: Extract Binary
        run: |
          docker create --name artifacts sentinelhub:latest
          docker cp artifacts:/usr/local/bin/sentinelhub ./sentinelhub
          docker rm artifacts

      - name: Generate SHA256 Checksum
        run: sha256sum sentinelhub > ./checksums.txt

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe #v2.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            checksums.txt
            sentinelhub
